Let's see if failing tests prevent merging

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -18,5 +18,5 @@ jobs:
     steps:
       - name: Just pass or fail immediately
         run: |
-          echo "we're passing!"
-          exit 0
+          echo "we're failing!"
+          exit 1
